import type { SourceConfig } from "../connectors/base.js";

export const defaultSources: SourceConfig[] = [
  // Tier 2 – Báo lớn, nhà báo uy tín
  {
    id: "vnexpress-thethao",
    type: "rss",
    tier: 2,
    url: "https://vnexpress.net/rss/the-thao.rss",
    rateLimitMinutes: 15,
    enabled: true,
  },
  {
    id: "tuoitre-thethao",
    type: "rss",
    tier: 2,
    url: "https://tuoitre.vn/rss/the-thao.rss",
    rateLimitMinutes: 15,
    enabled: true,
  },
  {
    id: "dantri-thethao",
    type: "rss",
    tier: 2,
    url: "https://dantri.com.vn/rss/the-thao.rss",
    rateLimitMinutes: 15,
    enabled: true,
  },
  {
    id: "zing-thethao",
    type: "rss",
    tier: 2,
    url: "https://zingnews.vn/rss/the-thao.rss",
    rateLimitMinutes: 15,
    enabled: true,
  },
  {
    id: "thanhnien-thethao",
    type: "rss",
    tier: 2,
    url: "https://thanhnien.vn/rss/the-thao.rss",
    rateLimitMinutes: 15,
    enabled: true,
  },
  {
    id: "vietnamnet-thethao",
    type: "rss",
    tier: 2,
    url: "https://vietnamnet.vn/rss/the-thao.rss",
    rateLimitMinutes: 15,
    enabled: true,
  },
  {
    id: "nld-thethao",
    type: "rss",
    tier: 2,
    url: "https://nld.com.vn/rss/the-thao.rss",
    rateLimitMinutes: 15,
    enabled: true,
  },
  // Tier 3 – Chuyên thể thao
  {
    id: "thethao247-thethao",
    type: "rss",
    tier: 3,
    url: "https://thethao247.vn/the-thao-24h.rss",
    rateLimitMinutes: 15,
    enabled: true,
  },
  {
    id: "thethao247-bongda",
    type: "rss",
    tier: 3,
    url: "https://thethao247.vn/bong-da.rss",
    rateLimitMinutes: 15,
    enabled: true,
  },
  {
    id: "thethao247-vleague",
    type: "rss",
    tier: 3,
    url: "https://thethao247.vn/v-league-c15.rss",
    rateLimitMinutes: 15,
    enabled: true,
  },
  {
    id: "thethao247-dtvn",
    type: "rss",
    tier: 3,
    url: "https://thethao247.vn/tuyen-quoc-gia-vn-c19.rss",
    rateLimitMinutes: 15,
    enabled: true,
  },
  {
    id: "thethao247-chuyennhuong",
    type: "rss",
    tier: 3,
    url: "https://thethao247.vn/chuyen-nhuong-c14.rss",
    rateLimitMinutes: 15,
    enabled: true,
  },
  {
    id: "thethao247-nha",
    type: "rss",
    tier: 3,
    url: "https://thethao247.vn/ngoai-hang-anh-c8.rss",
    rateLimitMinutes: 15,
    enabled: true,
  },
  {
    id: "thethao247-c1",
    type: "rss",
    tier: 3,
    url: "https://thethao247.vn/cup-c1-c13.rss",
    rateLimitMinutes: 15,
    enabled: true,
  },
  {
    id: "thethao247-vietnam",
    type: "rss",
    tier: 3,
    url: "https://thethao247.vn/bong-da-viet-nam-c1.rss",
    rateLimitMinutes: 15,
    enabled: true,
  },
  {
    id: "thethao247-livescore",
    type: "rss",
    tier: 3,
    url: "https://thethao247.vn/lich-thi-dau-bong-da-c54.rss",
    rateLimitMinutes: 15,
    enabled: true,
  },
  {
    id: "thethao247-ketqua",
    type: "rss",
    tier: 3,
    url: "https://thethao247.vn/ket-qua-bong-da-c55.rss",
    rateLimitMinutes: 15,
    enabled: true,
  },
  {
    id: "thethao247-bxh",
    type: "rss",
    tier: 3,
    url: "https://thethao247.vn/bang-xep-hang-bong-da-c56.rss",
    rateLimitMinutes: 15,
    enabled: true,
  },
  {
    id: "bongda24h-trangchu",
    type: "rss",
    tier: 3,
    url: "https://bongda24h.vn/RSS/1.rss",
    rateLimitMinutes: 15,
    enabled: true,
  },
  {
    id: "bongda24h-vietnam",
    type: "rss",
    tier: 3,
    url: "https://bongda24h.vn/RSS/168.rss",
    rateLimitMinutes: 15,
    enabled: true,
  },
  {
    id: "bongda24h-tinnong",
    type: "rss",
    tier: 3,
    url: "https://bongda24h.vn/RSS/279.rss",
    rateLimitMinutes: 15,
    enabled: true,
  },
  {
    id: "bongda24h-vleague",
    type: "rss",
    tier: 3,
    url: "https://bongda24h.vn/RSS/291.rss",
    rateLimitMinutes: 15,
    enabled: true,
  },
  {
    id: "bongda24h-dtvn",
    type: "rss",
    tier: 3,
    url: "https://bongda24h.vn/RSS/292.rss",
    rateLimitMinutes: 15,
    enabled: true,
  },
  // Bongda.com.vn – tin bóng đá số 1 VN
  {
    id: "bongda-trangchu",
    type: "rss",
    tier: 2,
    url: "https://bongda.com.vn/feed.rss",
    rateLimitMinutes: 15,
    enabled: true,
  },
  {
    id: "bongda-vietnam",
    type: "rss",
    tier: 2,
    url: "https://bongda.com.vn/viet-nam.rss",
    rateLimitMinutes: 15,
    enabled: true,
  },
  {
    id: "bongda-vleague",
    type: "rss",
    tier: 2,
    url: "https://bongda.com.vn/v-league.rss",
    rateLimitMinutes: 15,
    enabled: true,
  },
  {
    id: "bongda-chuyennhuong",
    type: "rss",
    tier: 2,
    url: "https://bongda.com.vn/tin-chuyen-nhuong.rss",
    rateLimitMinutes: 15,
    enabled: true,
  },
  {
    id: "bongda-c1",
    type: "rss",
    tier: 2,
    url: "https://bongda.com.vn/champions-league.rss",
    rateLimitMinutes: 15,
    enabled: true,
  },
  {
    id: "bongda-nha",
    type: "rss",
    tier: 2,
    url: "https://bongda.com.vn/bong-da-anh.rss",
    rateLimitMinutes: 15,
    enabled: true,
  },
  {
    id: "bongda-aff",
    type: "rss",
    tier: 2,
    url: "https://bongda.com.vn/aff-cup.rss",
    rateLimitMinutes: 15,
    enabled: true,
  },
  {
    id: "bongda-worldcup",
    type: "rss",
    tier: 2,
    url: "https://bongda.com.vn/world-cup.rss",
    rateLimitMinutes: 15,
    enabled: true,
  },
  // Tinthethao.com.vn
  {
    id: "tinthethao-trangchu",
    type: "rss",
    tier: 3,
    url: "https://www.tinthethao.com.vn/feed.rss",
    rateLimitMinutes: 15,
    enabled: true,
  },
  {
    id: "tinthethao-bongda",
    type: "rss",
    tier: 3,
    url: "https://www.tinthethao.com.vn/bong-da.rss",
    rateLimitMinutes: 15,
    enabled: true,
  },
  {
    id: "tinthethao-vietnam",
    type: "rss",
    tier: 3,
    url: "https://www.tinthethao.com.vn/bong-da-viet-nam.rss",
    rateLimitMinutes: 15,
    enabled: true,
  },
  {
    id: "tinthethao-vleague",
    type: "rss",
    tier: 3,
    url: "https://www.tinthethao.com.vn/v-league.rss",
    rateLimitMinutes: 15,
    enabled: true,
  },
  {
    id: "tinthethao-chuyennhuong",
    type: "rss",
    tier: 3,
    url: "https://www.tinthethao.com.vn/tin-chuyen-nhuong.rss",
    rateLimitMinutes: 15,
    enabled: true,
  },
  {
    id: "tinthethao-c1",
    type: "rss",
    tier: 3,
    url: "https://www.tinthethao.com.vn/champions-league.rss",
    rateLimitMinutes: 15,
    enabled: true,
  },
  // Bị tắt / cần kiểm tra
  {
    id: "bongdaplus-rss",
    type: "rss",
    tier: 2,
    url: "https://bongdaplus.vn/rss",
    rateLimitMinutes: 15,
    enabled: false, // trả về HTML, không phải RSS chuẩn
  },
];
