export const TOPIC_COLORS: Record<string, string> = {
  schedule: 'cyan',
  match_result: 'lime',
  vleague: 'green',
  nha: 'blue',
  c1: 'gold',
  c2: 'orange',
  c3: 'volcano',
  laliga: 'magenta',
  seriea: 'geekblue',
  bundesliga: 'volcano',
  ligue1: 'purple',
  afc_champions: 'gold',
  asian_cup: 'blue',
  aff: 'orange',
  sea_games: 'cyan',
  u23_asia: 'blue',
  worldcup: 'gold',
  euro: 'blue',
  copa_america: 'purple',
  nations_league: 'geekblue',
  caf: 'orange',
  olympic: 'gold',
  dtvn: 'red',
  transfer: 'purple',
  other: 'default',
};
